In [61]:
# 🟦 1. Aggregations (sum, mean, count,max,min etc.)
# Aggregation means combining data to produce summarized results.
# df["col"].sum()
# df["col"].mean()
# df["col"].count()
# df["col"].min()
# df["col"].max()
# df.agg({"col1": "sum", "col2": "mean"})
emp_df= pd.read_csv("emp.csv")
# emp_df["SAL"].mean()
emp_df.agg({"SAL":"sum","DEPTNO":"min","EMPNO":"max"})

SAL       39687.5
DEPTNO       10.0
EMPNO      7934.0
dtype: float64

In [65]:
# 🟩 2. Grouping Data → df.groupby()
# Grouping means splitting data into categories and performing operations per group.
# df.groupby("col")
# df.groupby(["col1", "col2"])
# df.groupby("col")["value_col"].agg(...)
# select deptno,sum(sal) from emo group by deptno; 
emp_df.groupby("DEPTNO")["SAL"].sum()
emp_df.groupby("DEPTNO")["SAL"].agg(["min","max","mean","sum"])

           min     max    mean      sum
DEPTNO
10      1560.0  6000.0  4520.0  13560.0
20      1040.0  3900.0  2255.5  11277.5
30      1425.0  4275.0  2475.0  14850.0

In [67]:
# 🟧 4. Apply Function → df.apply()
# apply() is used when you want to apply a custom function on:
# each column  :  df.apply(function)
# each row   : df.apply(function, axis=1)
import pandas as pd

df = pd.DataFrame({
    "a": [1, 2, 3],
    "b": [10, 20, 30]
})
df

   a   b
0  1  10
1  2  20
2  3  30

In [72]:
#  ✔ Example 1: Apply Column-wise
df.apply(lambda x:x.sum())
df.apply(lambda x:x.sum(),axis=0)

a     6
b    60
dtype: int64

In [73]:
#  ✔ Example 2: Apply Row-wise
df.apply(lambda x:x.sum(),axis=1)

0    11
1    22
2    33
dtype: int64

In [33]:
#  ✔ Example 3: Apply Custom Function

In [34]:
# 🟦 1. What is pd.merge()?
# pd.merge() combines two DataFrames based on a common column (called a key).
# It is similar to SQL joins.
select * from emp join/left join / right join dept on deptno=departmentno

In [35]:
# Syntax:
# pd.merge(
#     left=df1,
#     right=df2,
#     how="join_type",
#     on="column_name"
# )
# Parameters:
# left, right → DataFrames to merge
# how → type of join: "inner", "left", "right", "outer"
# on → column name to join on
# left_on, right_on → if column names differ
# indicator=True → shows match/mismatch status

In [92]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Aman", "Bhavya", "Chirag", "Divya"]
})

df2 = pd.DataFrame({
    "id12": [2, 3, 5],
    "salary": [50000, 60000, 45000]
})

In [83]:
#  5. Joining on Different Column Names (left_on, right_on)
inner_join_df =  pd.merge(
    left=df1,
    right=df2,
    how="inner",
    on="id"
)
inner_join_df

   id    name  salary
0   2  Bhavya   50000
1   3  Chirag   60000

In [84]:
left_join_df =  pd.merge(
    left=df1,
    right=df2,
    how="left",
    on="id"
)
left_join_df

   id    name   salary
0   1    Aman      NaN
1   2  Bhavya  50000.0
2   3  Chirag  60000.0
3   4   Divya      NaN

In [86]:
right_join_df =  pd.merge(
    left=df1,
    right=df2,
    how="right",
    on="id"
)
right_join_df

   id    name  salary
0   2  Bhavya   50000
1   3  Chirag   60000
2   5     NaN   45000

In [88]:
outer_join_df =  pd.merge(
    left=df1,
    right=df2,
    how="outer",
    on="id"
)
outer_join_df

   id    name   salary
0   1    Aman      NaN
1   2  Bhavya  50000.0
2   3  Chirag  60000.0
3   4   Divya      NaN
4   5     NaN  45000.0

In [95]:
#  method 2
outer_join_df =  df1.merge(
    df2,
    left_on="id",
    right_on="id12",
    how="outer"
    
)
outer_join_df

    id    name  id12   salary
0  1.0    Aman   NaN      NaN
1  2.0  Bhavya   2.0  50000.0
2  3.0  Chirag   3.0  60000.0
3  4.0   Divya   NaN      NaN
4  NaN     NaN   5.0  45000.0

In [38]:
# 🟨 6. Detecting Mismatches → indicator=True
# This helps in validating the join — shows where the row came from:
# left_only → present only in df1
# right_only → present only in df2
# both → successfully matched

In [96]:
#  pd.merge(df1, df2, on="id", how="outer", indicator=True)
outer_join_df =  df1.merge(
    df2,
    left_on="id",
    right_on="id12",
    how="outer",
    indicator=True
    
)
outer_join_df

    id    name  id12   salary      _merge
0  1.0    Aman   NaN      NaN   left_only
1  2.0  Bhavya   2.0  50000.0        both
2  3.0  Chirag   3.0  60000.0        both
3  4.0   Divya   NaN      NaN   left_only
4  NaN     NaN   5.0  45000.0  right_only

In [ ]:
# 🟪 7. How to filter unmatched rows

In [103]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["A", "B", "C", "D"]
})

df2 = pd.DataFrame({
    "id": [2, 4],
    "age": [30, 40]
})

In [100]:
#  ✅ Example 1: Get rows in df1 that DO NOT match df2
left_join_df =  pd.merge(
    left=df1,
    right=df2,
    how="left",
    on="id",
    indicator=True
)
left_join_df
left_only_records=left_join_df[left_join_df["_merge"]=="left_only"]
left_only_records

   id name  age     _merge
0   1    A  NaN  left_only
2   3    C  NaN  left_only

In [105]:
#  ✅ Example 2: Get rows in df2 that DO NOT match df1
#  ✅ Example 1: Get rows in df1 that DO NOT match df2
left_join_df =  pd.merge(
    left=df1,
    right=df2,
    how="right",
    on="id",
    indicator=True
)
left_join_df
left_only_records=left_join_df[left_join_df["_merge"]=="right_only"]
left_only_records

   id name  age _merge
0   2    B   30   both
1   4    D   40   both

In [43]:
#  🟦 1. Pivot → df.pivot()
# Pivot reshapes data by turning unique column values into new columns.
#  df.pivot(index="row_col", columns="column_to_expand", values="value_col")

In [107]:
import pandas as pd

df = pd.DataFrame({
    "name": ["A", "A", "B", "B"],
    "year": [2021, 2022, 2021, 2022],
    "sales": [100, 150, 200, 250]
})
df

pivoted = df.pivot(index="name", columns="year", values="sales")
print(pivoted)

year  2021  2022
name
A      100   150
B      200   250

In [45]:
#  🟩 2. Pivot Table → df.pivot_table()
# pivot_table() is smarter than pivot:
# Allows duplicates
# Allows aggregations (sum, mean…)

In [110]:
df = pd.DataFrame({
    "name": ["A", "A", "A", "B", "B"],
    "year": [2021, 2021, 2022, 2021, 2022],
    "sales": [100, 150, 130, 200, 250]
})
df
pivot_tbl = df.pivot_table(
    index="name",
    columns="year",
    values="sales",
    aggfunc="mean"
)

pivot_tbl

year   2021   2022
name
A     125.0  130.0
B     200.0  250.0

In [ ]:
#  🟥 3. Melt → pd.melt()
# Melt converts wide format → long format.
#  pd.melt(df, id_vars=[...], value_vars=[...], var_name="col", value_name="val")

In [111]:
df = pd.DataFrame({
    "name": ["A", "B"],
    "math": [90, 85],
    "science": [88, 92]
})

melted = pd.melt(
    df,
    id_vars=["name"],
    value_vars=["math", "science"],
    var_name="subject",
    value_name="marks"
)

print(melted)

  name  subject  marks
0    A     math     90
1    B     math     85
2    A  science     88
3    B  science     92

In [115]:
#  🟧 4. Replace → df.replace()
# Used to replace values in DataFrame.
#  df.replace(old_value, new_value)
#  df.replace({old1: new1, old2: new2})   
df = pd.DataFrame({
    "name": ["A", "B"],
    "city": ["A", "A"],
    "math": [90, 85],
    "science": [88, 92]
})
df
df.replace("A","B")

  name city  math  science
0    B    B    90       88
1    B    B    85       92

In [116]:
#  🟨 5. Map → df['col'].map()
#  Maps values of a column using a dictionary or function.
df = pd.DataFrame({
    "grade": ["A", "B", "C", "A"]
})

mapping = {"A": 90, "B": 80, "C": 70}

df["marks"] = df["grade"].map(mapping)        # Other method df.assign 
print(df)

  grade  marks
0     A     90
1     B     80
2     C     70
3     A     90