In [4]:
# 🟦 1. df['col'] — Selecting or Creating a Column single column return a series
# ✅ Select a column
import pandas as pd
df = pd.read_csv('emp.csv')
df["EMPNO"].reset_index()

    index  EMPNO
0       0   7839
1       1   7566
2       2   7698
3       3   7782
4       4   7902
5       5   7369
6       6   7499
7       7   7521
8       8   7654
9       9   7844
10     10   7876
11     11   7900
12     12   7934
13     13   7788

In [3]:
# ✅ Create a new column
df["df_sal_10additon"]= df["SAL"]+10
df

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,df_sal_10additon
0,7839,KING,PRESIDENT,NaN,17-NOV-81,6000.0,NaN,10,6010.0
1,7566,JONES,MANAGER,7839.0,02-APR-81,3867.5,NaN,20,3877.5
2,7698,BLAKE,MANAGER,7839.0,01-MAY-81,4275.0,NaN,30,4285.0
3,7782,CLARK,MANAGER,7839.0,09-JUN-81,6000.0,NaN,10,6010.0
4,7902,FORD,ANALYST,7566.0,03-DEC-81,1040.0,NaN,20,1050.0
5,7369,SMITH,CLERK,7902.0,17-DEC-80,1040.0,NaN,20,1050.0
6,7499,ALLEN,SALESMAN,7698.0,20-FEB-81,2400.0,300.0,30,2410.0
7,7521,WARD,SALESMAN,7698.0,22-FEB-81,2250.0,500.0,30,2260.0
8,7654,MARTIN,SALESMAN,7698.0,28-SEP-81,2250.0,1400.0,30,2260.0
9,7844,TURNER,SALESMAN,7698.0,08-SEP-81,2250.0,0.0,30,2260.0
10,7876,ADAMS,CLERK,7788.0,12-JAN-83,1430.0,NaN,20,1440.0
11,7900,JAMES,CLERK,7698.0,03-DEC-81,1425.0,NaN,30,1435.0
12,7934,MILLER,CLERK,7782.0,23-JAN-82,1560.0,NaN,10,1570.0
13,7788,SCOTT,ANALYST,7566.0,19-APR-87,3900.0,NaN,20,3910.0

In [5]:
# select miltiple column from the df
df[["SAL","JOB"]]

       SAL        JOB
0   6000.0  PRESIDENT
1   3867.5    MANAGER
2   4275.0    MANAGER
3   6000.0    MANAGER
4   1040.0    ANALYST
5   1040.0      CLERK
6   2400.0   SALESMAN
7   2250.0   SALESMAN
8   2250.0   SALESMAN
9   2250.0   SALESMAN
10  1430.0      CLERK
11  1425.0      CLERK
12  1560.0      CLERK
13  3900.0    ANALYST

In [3]:
# ✅ Create a new column
df["df_sal_10additon"]= df["SAL"]+10
df

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,df_sal_10additon
0,7839,KING,PRESIDENT,NaN,17-NOV-81,6000.0,NaN,10,6010.0
1,7566,JONES,MANAGER,7839.0,02-APR-81,3867.5,NaN,20,3877.5
2,7698,BLAKE,MANAGER,7839.0,01-MAY-81,4275.0,NaN,30,4285.0
3,7782,CLARK,MANAGER,7839.0,09-JUN-81,6000.0,NaN,10,6010.0
4,7902,FORD,ANALYST,7566.0,03-DEC-81,1040.0,NaN,20,1050.0
5,7369,SMITH,CLERK,7902.0,17-DEC-80,1040.0,NaN,20,1050.0
6,7499,ALLEN,SALESMAN,7698.0,20-FEB-81,2400.0,300.0,30,2410.0
7,7521,WARD,SALESMAN,7698.0,22-FEB-81,2250.0,500.0,30,2260.0
8,7654,MARTIN,SALESMAN,7698.0,28-SEP-81,2250.0,1400.0,30,2260.0
9,7844,TURNER,SALESMAN,7698.0,08-SEP-81,2250.0,0.0,30,2260.0
10,7876,ADAMS,CLERK,7788.0,12-JAN-83,1430.0,NaN,20,1440.0
11,7900,JAMES,CLERK,7698.0,03-DEC-81,1425.0,NaN,30,1435.0
12,7934,MILLER,CLERK,7782.0,23-JAN-82,1560.0,NaN,10,1570.0
13,7788,SCOTT,ANALYST,7566.0,19-APR-87,3900.0,NaN,20,3910.0

In [6]:
#  🟩 2. df.assign() — Create a new column (functional style)
# assign() returns a new DataFrame (does NOT modify original unless you save it).
df_sal10additon = df.assign(sal_10addition=df["SAL"]+10)
df_sal10additon

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,sal_10addition
0,7839,KING,PRESIDENT,NaN,17-NOV-81,6000.0,NaN,10,6010.0
1,7566,JONES,MANAGER,7839.0,02-APR-81,3867.5,NaN,20,3877.5
2,7698,BLAKE,MANAGER,7839.0,01-MAY-81,4275.0,NaN,30,4285.0
3,7782,CLARK,MANAGER,7839.0,09-JUN-81,6000.0,NaN,10,6010.0
4,7902,FORD,ANALYST,7566.0,03-DEC-81,1040.0,NaN,20,1050.0
5,7369,SMITH,CLERK,7902.0,17-DEC-80,1040.0,NaN,20,1050.0
6,7499,ALLEN,SALESMAN,7698.0,20-FEB-81,2400.0,300.0,30,2410.0
7,7521,WARD,SALESMAN,7698.0,22-FEB-81,2250.0,500.0,30,2260.0
8,7654,MARTIN,SALESMAN,7698.0,28-SEP-81,2250.0,1400.0,30,2260.0
9,7844,TURNER,SALESMAN,7698.0,08-SEP-81,2250.0,0.0,30,2260.0
10,7876,ADAMS,CLERK,7788.0,12-JAN-83,1430.0,NaN,20,1440.0
11,7900,JAMES,CLERK,7698.0,03-DEC-81,1425.0,NaN,30,1435.0
12,7934,MILLER,CLERK,7782.0,23-JAN-82,1560.0,NaN,10,1570.0
13,7788,SCOTT,ANALYST,7566.0,19-APR-87,3900.0,NaN,20,3910.0

In [8]:
#  🟥 3. df.drop() — Remove rows or columns
# Remove one column:
df2= df.drop(columns= ["DEPTNO"])
df2

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN

In [9]:
#  Remove multiple columns:
df2 = df.drop(columns=["JOB","SAL"])
df2

    EMPNO   ENAME     MGR   HIREDATE    COMM  DEPTNO
0    7839    KING     NaN  17-NOV-81     NaN      10
1    7566   JONES  7839.0  02-APR-81     NaN      20
2    7698   BLAKE  7839.0  01-MAY-81     NaN      30
3    7782   CLARK  7839.0  09-JUN-81     NaN      10
4    7902    FORD  7566.0  03-DEC-81     NaN      20
5    7369   SMITH  7902.0  17-DEC-80     NaN      20
6    7499   ALLEN  7698.0  20-FEB-81   300.0      30
7    7521    WARD  7698.0  22-FEB-81   500.0      30
8    7654  MARTIN  7698.0  28-SEP-81  1400.0      30
9    7844  TURNER  7698.0  08-SEP-81     0.0      30
10   7876   ADAMS  7788.0  12-JAN-83     NaN      20
11   7900   JAMES  7698.0  03-DEC-81     NaN      30
12   7934  MILLER  7782.0  23-JAN-82     NaN      10
13   7788   SCOTT  7566.0  19-APR-87     NaN      20

In [11]:
# Drop rows by index
df2= df.drop(index=[1,5,7,8,9])
df2

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL   COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0    NaN      10
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0    NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0    NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0    NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0  300.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0    NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0    NaN      30
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0    NaN      10
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0    NaN      20

In [21]:
# Drop with inplace
df = pd.read_csv("emp.csv")
df.drop(columns=["JOB","SAL"], inplace=True)
df

    EMPNO   ENAME     MGR   HIREDATE    COMM  DEPTNO
0    7839    KING     NaN  17-NOV-81     NaN      10
1    7566   JONES  7839.0  02-APR-81     NaN      20
2    7698   BLAKE  7839.0  01-MAY-81     NaN      30
3    7782   CLARK  7839.0  09-JUN-81     NaN      10
4    7902    FORD  7566.0  03-DEC-81     NaN      20
5    7369   SMITH  7902.0  17-DEC-80     NaN      20
6    7499   ALLEN  7698.0  20-FEB-81   300.0      30
7    7521    WARD  7698.0  22-FEB-81   500.0      30
8    7654  MARTIN  7698.0  28-SEP-81  1400.0      30
9    7844  TURNER  7698.0  08-SEP-81     0.0      30
10   7876   ADAMS  7788.0  12-JAN-83     NaN      20
11   7900   JAMES  7698.0  03-DEC-81     NaN      30
12   7934  MILLER  7782.0  23-JAN-82     NaN      10
13   7788   SCOTT  7566.0  19-APR-87     NaN      20

In [11]:
# 🟧 4. df.rename() — Rename columns or index

In [23]:
#  ✨ Rename columns
df = pd.read_csv("emp.csv")
df2=df.rename(columns={"JOB":"EJOB","SAL":"ESAL"})
df2

    EMPNO   ENAME       EJOB     MGR   HIREDATE    ESAL    COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN      10
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN      20

In [24]:
#  ✨ Rename rows (index)
df2=df.rename(index={0:"First_Row",1:"Second_Row"})
df2

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
First_Row,7839,KING,PRESIDENT,NaN,17-NOV-81,6000.0,NaN,10
Second_Row,7566,JONES,MANAGER,7839.0,02-APR-81,3867.5,NaN,20
2,7698,BLAKE,MANAGER,7839.0,01-MAY-81,4275.0,NaN,30
3,7782,CLARK,MANAGER,7839.0,09-JUN-81,6000.0,NaN,10
4,7902,FORD,ANALYST,7566.0,03-DEC-81,1040.0,NaN,20
5,7369,SMITH,CLERK,7902.0,17-DEC-80,1040.0,NaN,20
6,7499,ALLEN,SALESMAN,7698.0,20-FEB-81,2400.0,300.0,30
7,7521,WARD,SALESMAN,7698.0,22-FEB-81,2250.0,500.0,30
8,7654,MARTIN,SALESMAN,7698.0,28-SEP-81,2250.0,1400.0,30
9,7844,TURNER,SALESMAN,7698.0,08-SEP-81,2250.0,0.0,30
10,7876,ADAMS,CLERK,7788.0,12-JAN-83,1430.0,NaN,20
11,7900,JAMES,CLERK,7698.0,03-DEC-81,1425.0,NaN,30
12,7934,MILLER,CLERK,7782.0,23-JAN-82,1560.0,NaN,10
13,7788,SCOTT,ANALYST,7566.0,19-APR-87,3900.0,NaN,20

In [32]:
#  ✔ Convert ONE column
#  df["column"] = df["column"].astype(new_dtype)
 # ✔ Convert MULTIPLE columns
#  df = df.astype({
#     "col1": dtype1,
#     "col2": dtype2
# })
#  ✔ Convert MULTIPLE columns
df=pd.read_csv("emp.csv")
df.dtypes
#  df["column"] = df["column"].astype(new_dtype)
df["EMPNO"]=df["EMPNO"].astype(float)
df
# df = df.astype({
#     "col1": dtype1,
#     "col2": dtype2
# })
df2 = df.astype({"EMPNO":float,
                 "DEPTNO":float
                }) 
df2.dtypes

EMPNO       float64
ENAME        object
JOB          object
MGR         float64
HIREDATE     object
SAL         float64
COMM        float64
DEPTNO      float64
dtype: object

In [18]:
import pandas as pd

df = pd.DataFrame({
    "name": ["  Alice  ", "  Bob", "Charlie  "]
})
df["trimmed_name"] = df["name"].str.strip()

df

        name trimmed_name
0    Alice          Alice
1        Bob          Bob
2  Charlie        Charlie

In [ ]:
#  ✔ Handle errors 
pd.to_datetime(df["col"], errors="coerce")

In [33]:
# 🟦 1. Identify Missing Values
df = pd.DataFrame({"age": [25, None, 30]})
df.isna()

     age
0  False
1   True
2  False

In [36]:
df.isna()

     age
0  False
1   True
2  False

In [38]:
df[df["age"].isna()]

   age
1  NaN

In [39]:
df[df["age"].notna()]

    age
0  25.0
2  30.0

In [40]:
df["age"].isna().sum()  # Column wise none value count

np.int64(1)

In [20]:
#  🟩 2. Fill Missing Values → df.fillna()
# df.fillna(value)      # for all rows where none or null value present
# df.fillna({"col1": value1, "col2": value2})      # only for specific columns
# df["col"].fillna(value)                     # only one column

In [46]:
df = pd.DataFrame({"age": [25, None, 30],
                  "Sal": [None, 50000, None]})
df["age_filled"] = df["age"].fillna(0)
df
# specific Multiple column 
df2=df.fillna({"Sal": 100000,"age":143})
df2
# For all rows from the df
df.fillna(0)

    age      Sal  age_filled
0  25.0      0.0        25.0
1   0.0  50000.0         0.0
2  30.0      0.0        30.0

In [21]:
#  🟥 3. Drop Missing Values → df.dropna()
# df.dropna()                     # drop rows with ANY NaN
# df.dropna(how="all")            # drop rows with ALL NaN
# df.dropna(subset=["col"])       # drop rows where ONLY this column is NaN

In [54]:
df = pd.DataFrame({"ID":[1,5,3,None,None],"Sal":[100,None,300,400,None]})
df

    ID    Sal
0  1.0  100.0
1  5.0    NaN
2  3.0  300.0
3  NaN  400.0
4  NaN    NaN

In [55]:
# df.dropna()                     # drop rows with ANY NaN
df.dropna()

    ID    Sal
0  1.0  100.0
2  3.0  300.0

In [56]:
# df.dropna(how="all")            # drop rows with ALL NaN
df.dropna(how="all")

    ID    Sal
0  1.0  100.0
1  5.0    NaN
2  3.0  300.0
3  NaN  400.0

In [22]:
#  🟧 4. Duplicate Handling
# df.duplicated()                 # checks entire row
# df.duplicated(subset=["col"])   # check specific column

In [75]:
df = pd.DataFrame({"ID":[1,2,3,1,1],"Sal":[100,200,300,400,100]})
df
df.duplicated()                 # checks entire row
df[df.duplicated()]

   ID  Sal
4   1  100

In [76]:
# df.duplicated(subset=["col"])   # check specific column
df[df.duplicated(subset=["ID"])]

   ID  Sal
3   1  400
4   1  100

In [77]:
#  🔹 B) Remove duplicates → df.drop_duplicates()
# df.drop_duplicates()
# df.drop_duplicates(subset=["col"])
df = pd.DataFrame({"ID":[1,2,3,1,1],"Sal":[100,200,300,400,100]})
df

   ID  Sal
0   1  100
1   2  200
2   3  300
3   1  400
4   1  100

In [78]:
df.drop_duplicates()
#  df.drop_duplicates()

   ID  Sal
0   1  100
1   2  200
2   3  300
3   1  400

In [79]:
# df.drop_duplicates(subset=["col"])

df.drop_duplicates(subset=["ID"])

   ID  Sal
0   1  100
1   2  200
2   3  300

In [80]:
df = pd.DataFrame({
    "start": pd.to_datetime(["2023-01-01", "2023-01-10"]),
    "end":   pd.to_datetime(["2023-01-05", "2023-01-15"])
})

df["difference"] = df["end"] - df["start"]
df["difference"]

0   4 days
1   5 days
Name: difference, dtype: timedelta64[ns]