In [36]:
import pandas as pd

df = pd.DataFrame({
    "date": pd.to_datetime([
        "2023-05-21 14:30:10",
        "2024-01-10 09:15:00",
        "2022-12-31 23:59:59"
    ])
})

In [37]:
df.dtypes

date    datetime64[ns]
dtype: object

In [38]:
df=pd.read_csv('emp.csv', parse_dates=["HIREDATE"])
df.dtypes

C:\Users\MC\AppData\Local\Temp\ipykernel_608\3229159162.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df=pd.read_csv('emp.csv', parse_dates=["HIREDATE"])

EMPNO                int64
ENAME               object
JOB                 object
MGR                float64
HIREDATE    datetime64[ns]
SAL                float64
COMM               float64
DEPTNO               int64
dtype: object

In [39]:
#extract year from the date 
df["year"]=df["HIREDATE"].dt.year
df[["HIREDATE","year"]]

     HIREDATE  year
0  1981-11-17  1981
1  1981-04-02  1981
2  1981-05-01  1981
3  1981-06-09  1981
4  1981-12-03  1981
5  1980-12-17  1980
6  1981-02-20  1981
7  1981-02-22  1981
8  1981-09-28  1981
9  1981-09-08  1981
10 1983-01-12  1983
11 1981-12-03  1981
12 1982-01-23  1982
13 1987-04-19  1987

In [41]:
#extract month from the date 
df["HIREDATE"].dt.month.reset_index()

    index  HIREDATE
0       0        11
1       1         4
2       2         5
3       3         6
4       4        12
5       5        12
6       6         2
7       7         2
8       8         9
9       9         9
10     10         1
11     11        12
12     12         1
13     13         4

In [42]:
#extract day from the date 
df["HIREDATE"].dt.day_name().reset_index()

    index   HIREDATE
0       0    Tuesday
1       1   Thursday
2       2     Friday
3       3    Tuesday
4       4   Thursday
5       5  Wednesday
6       6     Friday
7       7     Sunday
8       8     Monday
9       9    Tuesday
10     10  Wednesday
11     11   Thursday
12     12   Saturday
13     13     Sunday

In [16]:
#extract month name from the date 
df["HIREDATE"].dt.month_name().reset_index()

    index   HIREDATE
0       0   November
1       1      April
2       2        May
3       3       June
4       4   December
5       5   December
6       6   February
7       7   February
8       8  September
9       9  September
10     10    January
11     11   December
12     12    January
13     13      April

In [17]:
#extract day name from the date 
df["HIREDATE"].dt.day_name().reset_index()

    index   HIREDATE
0       0    Tuesday
1       1   Thursday
2       2     Friday
3       3    Tuesday
4       4   Thursday
5       5  Wednesday
6       6     Friday
7       7     Sunday
8       8     Monday
9       9    Tuesday
10     10  Wednesday
11     11   Thursday
12     12   Saturday
13     13     Sunday

In [18]:
#extract datofweek name from the date 
df["HIREDATE"].dt.dayofweek.reset_index()

    index  HIREDATE
0       0         1
1       1         3
2       2         4
3       3         1
4       4         3
5       5         2
6       6         4
7       7         6
8       8         0
9       9         1
10     10         2
11     11         3
12     12         5
13     13         6

In [19]:
#extract year day number from the date 
df["HIREDATE"].dt.dayofyear.reset_index()

    index  HIREDATE
0       0       321
1       1        92
2       2       121
3       3       160
4       4       337
5       5       352
6       6        51
7       7        53
8       8       271
9       9       251
10     10        12
11     11       337
12     12        23
13     13       109

In [27]:
#extract quarter number the date 
df["HIREDATE"].dt.quarter.reset_index()

    index  HIREDATE
0       0         4
1       1         2
2       2         2
3       3         2
4       4         4
5       5         4
6       6         1
7       7         1
8       8         3
9       9         3
10     10         1
11     11         4
12     12         1
13     13         2

In [45]:
#extract week number from the date 
df["HIREDATE"].dt.isocalendar().week.reset_index()

    index  week
0       0    47
1       1    14
2       2    18
3       3    24
4       4    49
5       5    51
6       6     8
7       7     8
8       8    40
9       9    37
10     10     2
11     11    49
12     12     3
13     13    16