In [1]:
# df.isna() is a pandas function that checks for missing values (also called NaN, None, or NaT).
# It returns a DataFrame of booleans:
# True → the value is missing
# False → the value is NOT missing
# It is identical to df.isnull() (both do the same thing).

In [28]:
import pandas as pd

df = pd.DataFrame({
    "name": ["A", "B", None,None],
    "age": [23, None, 30,None]
})

df

   name   age
0     A  23.0
1     B   NaN
2  None  30.0
3  None   NaN

In [23]:
# ✅ 1. Count missing values Per column:
df.isna().sum()

name    1
age     1
dtype: int64

In [24]:
# Total missing value in df
df.isna().sum().sum()       
# sql       <------------------------------
# Pthon or pandas ----------------------------->

np.int64(2)

In [27]:
# ✅ 2. Filter rows with missing values
df[df.isna().any(axis=1)]

   name   age
1     B   NaN
2  None  30.0

In [29]:
#  Rows where ALL values are missing:
df[df.isna().all(axis=1)]

   name  age
3  None  NaN

In [33]:
# ✅ 3. Select rows where a specific column is missing
df[df[["age","name"]].isna()]

   name  age
0   NaN  NaN
1   NaN  NaN
2  None  NaN
3  None  NaN

In [34]:
# null check multiple columns
df[df[["age", "name"]].isna().any(axis=1)]

   name   age
1     B   NaN
2  None  30.0
3  None   NaN