In [1]:
import pandas as pd

In [2]:
#1️.filepath_or_buffer :Path or URL of the CSV. 
df = pd.read_csv("Data/emp.csv" )
df

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN      10
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN      20

In [3]:
#1️.filepath_or_buffer :File present in same project folder reading direct. 
df = pd.read_csv("emp.csv" )
df

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN      10
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN      20

In [4]:
# 2.️sep – delimiter:Default = ","  by defult it will take , 
df = pd.read_csv('emp.csv')
df

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN      10
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN      20

In [5]:
# File have | file delimiter 
df = pd.read_csv('emp1.csv',sep='|')
df

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN      10
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN      20

In [6]:
# File have | file delimiter 
df = pd.read_csv('emp1.csv',delimiter='|')
df

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN      10
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN      20

In [7]:
# 3️.header – which row contains column names:Default = first row (header=0)
df = pd.read_csv('emp.csv',header= None)   # It will header as 0,1,2,3,4,5,6,...... Insted of file header
df

        0       1          2     3          4       5     6       7
0   EMPNO   ENAME        JOB   MGR   HIREDATE     SAL  COMM  DEPTNO
1    7839    KING  PRESIDENT   NaN  17-NOV-81    6000   NaN      10
2    7566   JONES    MANAGER  7839  02-APR-81  3867.5   NaN      20
3    7698   BLAKE    MANAGER  7839  01-MAY-81    4275   NaN      30
4    7782   CLARK    MANAGER  7839  09-JUN-81    6000   NaN      10
5    7902    FORD    ANALYST  7566  03-DEC-81    1040   NaN      20
6    7369   SMITH      CLERK  7902  17-DEC-80    1040   NaN      20
7    7499   ALLEN   SALESMAN  7698  20-FEB-81    2400   300      30
8    7521    WARD   SALESMAN  7698  22-FEB-81    2250   500      30
9    7654  MARTIN   SALESMAN  7698  28-SEP-81    2250  1400      30
10   7844  TURNER   SALESMAN  7698  08-SEP-81    2250     0      30
11   7876   ADAMS      CLERK  7788  12-JAN-83    1430   NaN      20
12   7900   JAMES      CLERK  7698  03-DEC-81    1425   NaN      30
13   7934  MILLER      CLERK  7782  23-JAN-82    1560   NaN      10
14   7788   SCOTT    ANALYST  7566  19-APR-87    3900   NaN      20

In [8]:
df = pd.read_csv('emp.csv',header= 1)   # It will set row 1 as Headers
df

    7839    KING PRESIDENT  Unnamed: 3  17-NOV-81    6000  Unnamed: 6  10
0   7566   JONES   MANAGER        7839  02-APR-81  3867.5         NaN  20
1   7698   BLAKE   MANAGER        7839  01-MAY-81  4275.0         NaN  30
2   7782   CLARK   MANAGER        7839  09-JUN-81  6000.0         NaN  10
3   7902    FORD   ANALYST        7566  03-DEC-81  1040.0         NaN  20
4   7369   SMITH     CLERK        7902  17-DEC-80  1040.0         NaN  20
5   7499   ALLEN  SALESMAN        7698  20-FEB-81  2400.0       300.0  30
6   7521    WARD  SALESMAN        7698  22-FEB-81  2250.0       500.0  30
7   7654  MARTIN  SALESMAN        7698  28-SEP-81  2250.0      1400.0  30
8   7844  TURNER  SALESMAN        7698  08-SEP-81  2250.0         0.0  30
9   7876   ADAMS     CLERK        7788  12-JAN-83  1430.0         NaN  20
10  7900   JAMES     CLERK        7698  03-DEC-81  1425.0         NaN  30
11  7934  MILLER     CLERK        7782  23-JAN-82  1560.0         NaN  10
12  7788   SCOTT   ANALYST        7566  19-APR-87  3900.0         NaN  20

In [9]:
# 4️.names – custom column names :Use when header=None.
df = pd.read_csv('emp.csv',header=None,names=["Eno","ename","Job","MGR","Hiredate","Esal","Comm","Edeptno"],skiprows=1)  # skip rows removing File header
df

     Eno   ename        Job     MGR   Hiredate    Esal    Comm  Edeptno
0   7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN       10
1   7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN       20
2   7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN       30
3   7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN       10
4   7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN       20
5   7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN       20
6   7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0       30
7   7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0       30
8   7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0       30
9   7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0       30
10  7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN       20
11  7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN       30
12  7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN       10
13  7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN       20

In [10]:
# 5️.index_col – make a column the index  : By defuult Pandas will givr indexes as 0,1,2,3,.... when we want to make any columns as index then we
# use the option as index_col
df = pd.read_csv('emp.csv',index_col="EMPNO")
df

        ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
EMPNO
7839     KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
7566    JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
7698    BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
7782    CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
7902     FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
7369    SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
7499    ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7521     WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
7654   MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
7844   TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
7876    ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
7900    JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30
7934   MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN      10
7788    SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN      20

In [11]:
# Multiple column as index
df = pd.read_csv('emp.csv', index_col=['EMPNO', 'DEPTNO'])
df

               ENAME        JOB     MGR   HIREDATE     SAL    COMM
EMPNO DEPTNO
7839  10        KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN
7566  20       JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN
7698  30       BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN
7782  10       CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN
7902  20        FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN
7369  20       SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN
7499  30       ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0
7521  30        WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0
7654  30      MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0
7844  30      TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0
7876  20       ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN
7900  30       JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN
7934  10      MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN
7788  20       SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN

In [12]:
# Pass index as index or using column indexes:
df = pd.read_csv('emp.csv', index_col=[0, 2])
df

                  ENAME     MGR   HIREDATE     SAL    COMM  DEPTNO
EMPNO JOB
7839  PRESIDENT    KING     NaN  17-NOV-81  6000.0     NaN      10
7566  MANAGER     JONES  7839.0  02-APR-81  3867.5     NaN      20
7698  MANAGER     BLAKE  7839.0  01-MAY-81  4275.0     NaN      30
7782  MANAGER     CLARK  7839.0  09-JUN-81  6000.0     NaN      10
7902  ANALYST      FORD  7566.0  03-DEC-81  1040.0     NaN      20
7369  CLERK       SMITH  7902.0  17-DEC-80  1040.0     NaN      20
7499  SALESMAN    ALLEN  7698.0  20-FEB-81  2400.0   300.0      30
7521  SALESMAN     WARD  7698.0  22-FEB-81  2250.0   500.0      30
7654  SALESMAN   MARTIN  7698.0  28-SEP-81  2250.0  1400.0      30
7844  SALESMAN   TURNER  7698.0  08-SEP-81  2250.0     0.0      30
7876  CLERK       ADAMS  7788.0  12-JAN-83  1430.0     NaN      20
7900  CLERK       JAMES  7698.0  03-DEC-81  1425.0     NaN      30
7934  CLERK      MILLER  7782.0  23-JAN-82  1560.0     NaN      10
7788  ANALYST     SCOTT  7566.0  19-APR-87  3900.0     NaN      20

In [13]:
# 6️.dtype – explicitly set datatypes  when want to change some column data type then we use this option 
df = pd.read_csv('emp.csv')   # Intially checking the defult data types
df.dtypes

EMPNO         int64
ENAME        object
JOB          object
MGR         float64
HIREDATE     object
SAL         float64
COMM        float64
DEPTNO        int64
dtype: object

In [14]:
# 6️.dtype – explicitly set datatypes  when want to change some column data type then we use this option 
df = pd.read_csv('emp.csv',dtype={"DEPTNO":"int","EMPNO":"float","ENAME":"string"})  #Dtype we can pass "" or simple but string should be "string"
df.dtypes

EMPNO              float64
ENAME       string[python]
JOB                 object
MGR                float64
HIREDATE            object
SAL                float64
COMM               float64
DEPTNO               int64
dtype: object

In [15]:
#The parse_dates parameter in pd.read_csv() tells pandas to convert one or more columns into datetime64 objects as the file is loaded.
#Normally, date columns are read as strings.
#parse_dates turns them into real datetime objects, which allows:
#date filtering
#calculating durations
#resampling (daily, monthly, yearly)
#extracting year/month/day
#sorting by date correctly"""

df = pd.read_csv("emp.csv", parse_dates=["HIREDATE"])
df.dtypes

C:\Users\MC\AppData\Local\Temp\ipykernel_3488\3196614901.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("emp.csv", parse_dates=["HIREDATE"])

EMPNO                int64
ENAME               object
JOB                 object
MGR                float64
HIREDATE    datetime64[ns]
SAL                float64
COMM               float64
DEPTNO               int64
dtype: object

In [16]:
# Result:
# DOJ becomes dtype: datetime64[ns]
# Now you can do:

df[df["HIREDATE"]< "1981-02-22"]

   EMPNO  ENAME       JOB     MGR   HIREDATE     SAL   COMM  DEPTNO
5   7369  SMITH     CLERK  7902.0 1980-12-17  1040.0    NaN      20
6   7499  ALLEN  SALESMAN  7698.0 1981-02-20  2400.0  300.0      30

In [17]:
# Example 2 — Parse multiple date columns
# df = pd.read_csv("emp.csv", parse_dates=["DOJ", "DOB"])

In [26]:
# 8. na_values – treat extra strings as NaN (missing values)
# When reading a CSV, pandas automatically treats some values as NaN (missing), like:
# empty cells
# "NA"
# "NaN"
# "null"
# But real-world CSV files often contain custom missing-value markers, such as:
# "?"
# "N/A"
# "None"
# "missing"
# "—"
# "no data"
# The na_values parameter lets you tell pandas which extra strings should be considered missing (NaN).
# ✔ 1. Single value
# Treat "?" as NaN:
df = pd.read_csv("emp.csv", na_values="?")
# ✔ 2. Multiple missing-value markers
df = pd.read_csv("emp.csv", na_values=["?", "N/A", "none", "-"])  # Now all of them become real NaN.
# When we want to use for different columns then 
df = pd.read_csv(
    "emp.csv",
    na_values={
        "ENAME": ["NoName"],
        "SAL": [-1],
        "DEPTNO": [999]
    }
)
df

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30
12   7934  MILLER      CLERK  7782.0  23-JAN-82  1560.0     NaN      10
13   7788   SCOTT    ANALYST  7566.0  19-APR-87  3900.0     NaN      20

In [29]:
# ❗ What happens when you set keep_default_na=False?
# You tell pandas:
# “Do NOT treat the usual strings like ‘NA’, ‘N/A’, ‘None’, ‘nan’ as missing.
# Only treat missing values I specify in na_values.”
# So pandas stops its automatic NA detection.

In [32]:
# Tom,N/A
# ✔ Case 1 — Default behavior (keep_default_na=True)  # “NA” and “N/A” become NaN automatically.
# ✔ Case 2 — Disable default NA detection # df = pd.read_csv("emp.csv", keep_default_na=False)
# ✔ Case 3 — Combine with custom missing values
df = pd.read_csv(
    "emp.csv",
    keep_default_na=False,
    na_values=["???", "none", "--"]
)
df

    EMPNO   ENAME        JOB   MGR   HIREDATE     SAL  COMM  DEPTNO
0    7839    KING  PRESIDENT        17-NOV-81  6000.0            10
1    7566   JONES    MANAGER  7839  02-APR-81  3867.5            20
2    7698   BLAKE    MANAGER  7839  01-MAY-81  4275.0            30
3    7782   CLARK    MANAGER  7839  09-JUN-81  6000.0            10
4    7902    FORD    ANALYST  7566  03-DEC-81  1040.0            20
5    7369   SMITH      CLERK  7902  17-DEC-80  1040.0            20
6    7499   ALLEN   SALESMAN  7698  20-FEB-81  2400.0   300      30
7    7521    WARD   SALESMAN  7698  22-FEB-81  2250.0   500      30
8    7654  MARTIN   SALESMAN  7698  28-SEP-81  2250.0  1400      30
9    7844  TURNER   SALESMAN  7698  08-SEP-81  2250.0     0      30
10   7876   ADAMS      CLERK  7788  12-JAN-83  1430.0            20
11   7900   JAMES      CLERK  7698  03-DEC-81  1425.0            30
12   7934  MILLER      CLERK  7782  23-JAN-82  1560.0            10
13   7788   SCOTT    ANALYST  7566  19-APR-87  3900.0            20

In [33]:
# 📌 10. nrows – read only X rows from a CSV
# The nrows parameter tells pandas to read only the first N rows of the CSV file.
# It is extremely useful when:
# your file is very large
# you want to preview the data
# you want to test code quickly
# you want to load only a small portion of the dataset
df = pd.read_csv("emp.csv", nrows=5)
df

   EMPNO  ENAME        JOB     MGR   HIREDATE     SAL  COMM  DEPTNO
0   7839   KING  PRESIDENT     NaN  17-NOV-81  6000.0   NaN      10
1   7566  JONES    MANAGER  7839.0  02-APR-81  3867.5   NaN      20
2   7698  BLAKE    MANAGER  7839.0  01-MAY-81  4275.0   NaN      30
3   7782  CLARK    MANAGER  7839.0  09-JUN-81  6000.0   NaN      10
4   7902   FORD    ANALYST  7566.0  03-DEC-81  1040.0   NaN      20

In [34]:
sample = pd.read_csv("emp.csv", nrows=10)
sample

   EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0   7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1   7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2   7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3   7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4   7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5   7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6   7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7   7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8   7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9   7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30

In [35]:
# 📌 11. skiprows – skip rows at the start (or anywhere)
# The skiprows parameter tells pandas:
# “Do not read these rows from the CSV file.”
# You can skip:
# the first few rows
# a specific list of rows
# rows that match a condition (using a function)
# skiprows is extremely useful when your CSV contains:
# metadata or notes at the top
# unnecessary header information
# blank rows
# bad rows
# multiple header lines

In [37]:
# ✅ 1. Skip first N rows
# This is the most common usage.
# Example: skip the first 2 rows
df = pd.read_csv("emp.csv", skiprows=2) # This removes rows 0 and 1 (index in the file, not DataFrame index).
df

    7566   JONES   MANAGER  7839  02-APR-81  3867.5  Unnamed: 6  20
0   7698   BLAKE   MANAGER  7839  01-MAY-81    4275         NaN  30
1   7782   CLARK   MANAGER  7839  09-JUN-81    6000         NaN  10
2   7902    FORD   ANALYST  7566  03-DEC-81    1040         NaN  20
3   7369   SMITH     CLERK  7902  17-DEC-80    1040         NaN  20
4   7499   ALLEN  SALESMAN  7698  20-FEB-81    2400       300.0  30
5   7521    WARD  SALESMAN  7698  22-FEB-81    2250       500.0  30
6   7654  MARTIN  SALESMAN  7698  28-SEP-81    2250      1400.0  30
7   7844  TURNER  SALESMAN  7698  08-SEP-81    2250         0.0  30
8   7876   ADAMS     CLERK  7788  12-JAN-83    1430         NaN  20
9   7900   JAMES     CLERK  7698  03-DEC-81    1425         NaN  30
10  7934  MILLER     CLERK  7782  23-JAN-82    1560         NaN  10
11  7788   SCOTT   ANALYST  7566  19-APR-87    3900         NaN  20

In [38]:
df = pd.read_csv("emp.csv", skiprows=2) # This removes rows 0 and 1 (index in the file, not DataFrame index).
df

    7566   JONES   MANAGER  7839  02-APR-81  3867.5  Unnamed: 6  20
0   7698   BLAKE   MANAGER  7839  01-MAY-81    4275         NaN  30
1   7782   CLARK   MANAGER  7839  09-JUN-81    6000         NaN  10
2   7902    FORD   ANALYST  7566  03-DEC-81    1040         NaN  20
3   7369   SMITH     CLERK  7902  17-DEC-80    1040         NaN  20
4   7499   ALLEN  SALESMAN  7698  20-FEB-81    2400       300.0  30
5   7521    WARD  SALESMAN  7698  22-FEB-81    2250       500.0  30
6   7654  MARTIN  SALESMAN  7698  28-SEP-81    2250      1400.0  30
7   7844  TURNER  SALESMAN  7698  08-SEP-81    2250         0.0  30
8   7876   ADAMS     CLERK  7788  12-JAN-83    1430         NaN  20
9   7900   JAMES     CLERK  7698  03-DEC-81    1425         NaN  30
10  7934  MILLER     CLERK  7782  23-JAN-82    1560         NaN  10
11  7788   SCOTT   ANALYST  7566  19-APR-87    3900         NaN  20

In [41]:
# ✅ 2. Skip specific rows (using list)
# If you only want to skip certain lines, use a list.
# Example: skip rows 1 and 3
df = pd.read_csv("emp.csv", skiprows=[1, 3])
df

    EMPNO   ENAME       JOB   MGR   HIREDATE     SAL    COMM  DEPTNO
0    7566   JONES   MANAGER  7839  02-APR-81  3867.5     NaN      20
1    7782   CLARK   MANAGER  7839  09-JUN-81  6000.0     NaN      10
2    7902    FORD   ANALYST  7566  03-DEC-81  1040.0     NaN      20
3    7369   SMITH     CLERK  7902  17-DEC-80  1040.0     NaN      20
4    7499   ALLEN  SALESMAN  7698  20-FEB-81  2400.0   300.0      30
5    7521    WARD  SALESMAN  7698  22-FEB-81  2250.0   500.0      30
6    7654  MARTIN  SALESMAN  7698  28-SEP-81  2250.0  1400.0      30
7    7844  TURNER  SALESMAN  7698  08-SEP-81  2250.0     0.0      30
8    7876   ADAMS     CLERK  7788  12-JAN-83  1430.0     NaN      20
9    7900   JAMES     CLERK  7698  03-DEC-81  1425.0     NaN      30
10   7934  MILLER     CLERK  7782  23-JAN-82  1560.0     NaN      10
11   7788   SCOTT   ANALYST  7566  19-APR-87  3900.0     NaN      20

In [42]:
# ✅ 3. Skip rows using a function (advanced but powerful)
# You can pass a function that returns True for rows you want to skip.
# Example: skip all rows starting with #
# Comment
# More comments
EMPNO,ENAME,SAL
101,John,3000
df = pd.read_csv("emp.csv", skiprows=lambda x: x < 2) # This skips the first two rows

NameError: name 'EMPNO' is not defined

In [43]:
# ✅ 4. Skip a range + read only some rows
# Often used with nrows to read specific blocks from large CSVs.
# Example: read rows 100–199
df = pd.read_csv("emp.csv", skiprows=5, nrows=13)
df

   7902    FORD   ANALYST  7566  03-DEC-81  1040  Unnamed: 6  20
0  7369   SMITH     CLERK  7902  17-DEC-80  1040         NaN  20
1  7499   ALLEN  SALESMAN  7698  20-FEB-81  2400       300.0  30
2  7521    WARD  SALESMAN  7698  22-FEB-81  2250       500.0  30
3  7654  MARTIN  SALESMAN  7698  28-SEP-81  2250      1400.0  30
4  7844  TURNER  SALESMAN  7698  08-SEP-81  2250         0.0  30
5  7876   ADAMS     CLERK  7788  12-JAN-83  1430         NaN  20
6  7900   JAMES     CLERK  7698  03-DEC-81  1425         NaN  30
7  7934  MILLER     CLERK  7782  23-JAN-82  1560         NaN  10
8  7788   SCOTT   ANALYST  7566  19-APR-87  3900         NaN  20

In [46]:
# 📌 12. skipfooter – skip rows at the bottom of the file
# skiprows removes rows from the top
# skipfooter removes rows from the bottom
# ❗ But why do we need engine="python"?
# By default, pandas uses the C engine for reading CSV—fast but limited.
# The C engine cannot handle skipfooter. So pandas requires:
df=pd.read_csv("emp.csv", skipfooter=2, engine="python")
df

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0    7839    KING  PRESIDENT     NaN  17-NOV-81  6000.0     NaN      10
1    7566   JONES    MANAGER  7839.0  02-APR-81  3867.5     NaN      20
2    7698   BLAKE    MANAGER  7839.0  01-MAY-81  4275.0     NaN      30
3    7782   CLARK    MANAGER  7839.0  09-JUN-81  6000.0     NaN      10
4    7902    FORD    ANALYST  7566.0  03-DEC-81  1040.0     NaN      20
5    7369   SMITH      CLERK  7902.0  17-DEC-80  1040.0     NaN      20
6    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  2400.0   300.0      30
7    7521    WARD   SALESMAN  7698.0  22-FEB-81  2250.0   500.0      30
8    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  2250.0  1400.0      30
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  2250.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-83  1430.0     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81  1425.0     NaN      30

In [47]:
# 📌 13. chunksize – load file in chunks (iterator / generator)
# When you set chunksize, pandas does not load the entire CSV into memory.
# Instead, it reads the file piece by piece (chunk by chunk).
# Each chunk is returned as a DataFrame, and you can process each chunk incrementally.
# This is extremely helpful when working with:
# very large CSV files (GB-sized)
# low RAM systems ,stream processing. batch processing

In [49]:
#Example 1 — Read in chunks of 500 rows
for chunk in pd.read_csv("emp.csv", chunksize=5):
    print(chunk)

   EMPNO  ENAME        JOB     MGR   HIREDATE     SAL  COMM  DEPTNO
0   7839   KING  PRESIDENT     NaN  17-NOV-81  6000.0   NaN      10
1   7566  JONES    MANAGER  7839.0  02-APR-81  3867.5   NaN      20
2   7698  BLAKE    MANAGER  7839.0  01-MAY-81  4275.0   NaN      30
3   7782  CLARK    MANAGER  7839.0  09-JUN-81  6000.0   NaN      10
4   7902   FORD    ANALYST  7566.0  03-DEC-81  1040.0   NaN      20
   EMPNO   ENAME       JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
5   7369   SMITH     CLERK  7902  17-DEC-80  1040     NaN      20
6   7499   ALLEN  SALESMAN  7698  20-FEB-81  2400   300.0      30
7   7521    WARD  SALESMAN  7698  22-FEB-81  2250   500.0      30
8   7654  MARTIN  SALESMAN  7698  28-SEP-81  2250  1400.0      30
9   7844  TURNER  SALESMAN  7698  08-SEP-81  2250     0.0      30
    EMPNO   ENAME      JOB   MGR   HIREDATE   SAL  COMM  DEPTNO
10   7876   ADAMS    CLERK  7788  12-JAN-83  1430   NaN      20
11   7900   JAMES    CLERK  7698  03-DEC-81  1425   NaN      30
12   7934  MILLER    CLERK  7782  23-JAN-82  1560   NaN      10
13   7788   SCOTT  ANALYST  7566  19-APR-87  3900   NaN      20

In [50]:
# 📘 Example 2 — Count total number of rows in a huge file
total = 0
for chunk in pd.read_csv("emp.csv", chunksize=1000):
    total += len(chunk)

print("Total rows:", total)

Total rows: 14

In [52]:
# 📘 Example 3 — Process data chunk-by-chunk
total_salary = 0

for chunk in pd.read_csv("emp.csv", chunksize=10000):
    total_salary += chunk['SAL'].sum()

print(total_salary)

39687.5

In [ ]:
# 14. memory_map

#Enables memory-mapped file access to speed up reading extremely large CSV files without loading them fully into RAM.
# 15. error_bad_lines=False (deprecated)

# Older option that told pandas to skip malformed or too-long lines instead of raising an error.
# 16. on_bad_lines
# error – raise an error when a bad line is found (default).
# skip – silently skip malformed lines.
# warn – show a warning and skip malformed lines